### ISSUE TITLE
Column names? 

### ISSUE THREAD

**Issue by orb16** [philiprenich/nz-covid19-data#1]
The previous version could be read in (I'm using R and jsonlite) and had the same column names as the MoH spreadsheet. Looks like the nz-covid-cases.json is now using the contents of the first row as the column names?

**Comment by philiprenich** [comment]
Thanks for the heads up. I missed an adjustment to their spreadsheet structure yesterday when updating. But turns out they changed it again today! So both changes should be accounted for now. The automation worked too and the file has just been updated :)

Cheers! I'll try to keep tabs on their format, but let me know if something goes off again. Would love to see how you use the data!
